alias v='vim'
alias sv='sudo vim'
alias vf='vim $(fzf)'
alias svf='sudo vim $(fzf)'
alias dakpi='ssh 192.168.1.69'
alias bashcfg='vim ~/.bashrc'
alias addalias='vim ~/.bash_aliases'
alias bashsrc='source ~/.bashrc'
alias vcfg='vim ~/.vimrc'
alias config='/usr/bin/git --git-dir=/home/dakahn/.cfg/ --work-tree=/home/dakahn'

